services:
  - type: web
    name: kontanos
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_URL
        value: https://kontanos.onrender.com
      - key: COOKIE_SECURE
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: kontanos-db
          property: connectionString
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FACEBOOK_APP_ID
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false
      - key: IMGBB_API_KEY
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false

databases:
  - name: kontanos-db
    plan: free
    databaseName: kontactanos
